### PR TITLE
Try escaping quotes

### LINKED ISSUE #21: Use execFileSync or similar passing the arguments as arrays instead of a single command string
The extraction code fails on windows and other platforms

Here's the error message from windows
```
Error: 'publicLogError2'' is not recognized as an internal or external command,
operable program or batch file.
```

I managed to get this working on Windows by changing the following code
```const text = "const retrieved_paths = cp.execSync(cmd, { encoding: 'ascii' });";```
to 
```const retrieved_paths = cp.execFileSync(ripgrep_1.rgPath, ['--files-with-matches', '--glob', '**/*.ts', '--no-ignore', 'publicLog2|publicLogError2', this.sourceDir], { encoding: 'ascii' });";```

With the former some how `publicLogError2` ends up as a piping operation, I guess the character `|` some how triggers that behaviour (possible due to incorrectly escaped arguments or the like).

I would suggest changing this everywhere where we use `execSync`
Also would suggest logging the errors, today the errors are swallowed, and its possible we're ignoring all such errors due to the empty `catch { }`.

### PR DESCRIPTION
**Pull request by lramos15**
Attempt to fix #21

The suggested fix of `execFileSync` does not appear to work and causes all tests to fail. My guess is that there is a quoting problem, so here we try and escape the quotes.

### CODE REVIEW

File: src/lib/ts-parser.ts [hunk 1]
```diff
@@ -132,7 +132,7 @@ export class TsParser {
         for (const fg of fileGlobs) {
             rg_glob += ` --glob ${fg}`;
         }
-        const cmd = `${rgPath} --files-with-matches ${rg_glob} --no-ignore 'publicLog2|publicLogError2' ${this.sourceDir}`;
+        const cmd = `${rgPath} --files-with-matches ${rg_glob} --no-ignore \"publicLog2|publicLogError2\" ${this.sourceDir}`;
```
Comment (DonJayamanne) [inline src/lib/ts-parser.ts:135]: Why double quotes, 
In line 129 we have single quotes, feels weird to mix quotes, i would have expected this to work with either one.
